#Not exposed outside cluster
apiVersion: v1
kind: Service
metadata:
  name: canaryservicev1
  labels: 
    app: canary-test
spec:
  type: ClusterIP
  ports:
  - protocol: TCP
    port: 8300
  selector:
     app: canary-test
     version: v1
