---
apiVersion: v1
kind: Service
metadata:
  labels:
    service: ambassador
  name: ambassador
  annotations:
    getambassador.io/config: |
      ---
      apiVersion: ambassador/v0
      kind:  Mapping
      name:  canaryv1mapping
      prefix: /
      timeout_ms: 60000
      service: canaryservicev1:8300
      ---
      apiVersion: ambassador/v0
      kind:  Mapping
      name:  canaryv2mapping
      prefix: /
      headers:
        test: canary-test
      timeout_ms: 60000
      service: canaryservicev2:8300
spec:
  type: LoadBalancer
  ports:
  - name: ambassador
    port: 80
    targetPort: 8080
  selector:
    service: ambassador